# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.5 on 2026-06-04 23:02

from django.db import migrations, models

import weblate.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0077_merge_20260506_0746"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="filemask",
            field=models.CharField(
                help_text="Path of files to translate relative to repository root, use * instead of language code, for example: po/*.po or locale/*/LC_MESSAGES/django.po.",
                max_length=400,
                validators=[weblate.utils.validators.validate_filename],
                verbose_name="File mask",
            ),
        ),
    ]
